//main
export const FETCH_MAIN_DATA='FETCH_MAIN_DATA';
//login
export const FETCH_LOGIN_SUCCESS='FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE='FETCH_LOGIN_FAILURE';
export const FETCH_LOGOUT='FETCH_LOGOUT';
//hotel
export const FETCH_HOTEL_LIST='FETCH_HOTEL_LIST';
export const FETCH_HOTEL_DETAIL='FETCH_HOTEL_DETAIL';
export const FETCH_HOTEL_FIND='FETCH_HOTEL_FIND';
//food

//youtube
export const FETCH_YOUTUBE_FIND='FETCH_YOUTUBE_FIND'
//news
export const NEWS_LIST='NEWS_LIST'
//board
export const RESET = 'RESET'
export const BOARD_LIST='BOARD_LIST'
export const BOARD_DETAIL='BOARD_DETAIL'
export const BOARD_INSERT='BOARD_INSERT'
export const BOARD_DELETE='BOARD_DELETE'
export const BOARD_UPDATE='BOARD_UPDATE'
export const BOARD_UPDATE_OK='BOARD_UPDATE_OK'